debug: true
autologin: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiaohe66-web?characterEncoding=UTF-8&useUnicode=true&autoReconnect=true&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    cache: false
  resources:
    static-locations: file:${project.build.directory}/res/static/

server:
  port: 8080

logging:
  file:
    path: logs/

xiaohe66:
  file:
    home: C:\\xiaohe66\\file\\
    maxMbChunkPer: 1
    maxMbFilePer: 8
  registerUrl: http://localhost/sec/login/register/
  wx:
    miniProgramState: developer
    appId: appid
    appSecret: secret