#--------------------------------------------
spring:
  resources:
    # 配置静态资源路径，默认配置失效[public、static、META-INF/resource]
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /**
  thymeleaf:
    prefix: classpath:/template
  datasource:
    hikari:
      # 最小空闲时连接数
      minimum-idle: 2
#-------------------------------------------
server:
  tomcat:
    # 配置Tomcat编码,默认为UTF-8
    uri-encoding: UTF-8
#------------- mybatis ---------------------------------
mybatis-plus:
  global-config:
    db-config:
      id-type: input
#------------- logback ---------------------------------
# 输出格式：
# %line 行号
# %M  方法名
logging:
  config: classpath:logback-spring.xml
  pattern:
    console: '%d{HH:mm:ss.SSS} %highlight[%-5p] [%thread] %cyan(%logger{15}) - %msg %n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5p] [%thread] %logger{30} - %msg %n'
  file:
    path: logs/

#------------- shrio ---------------------------------
#配置性参数
xiaohe66:
  wx:
    miniProgramState: developer
    appId: appid
    appSecret: secret