spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/xiaohe66-web?characterEncoding=UTF-8&useUnicode=true&autoReconnect=true&useSSL=false&serverTimezone=GMT
    username: xiaohe66-web
    password: xiaohe66-web

server:
  port: 8081

xiaohe66:
  file:
    pictureDirectory: C:\\xiaohe66\\file\\picture
    imageDirectory: C:\\xiaohe66\\file\\image
  wx:
    task:
      miniProgramState: developer
      appId: appid_todo
      appSecret: secret_todo
    love:
      miniProgramState: developer
      appId: appid_love
      appSecret: secret_love
